### ISSUE TITLE
scala.ScalaReflectionException: object org.danielnixon.playwarts.FutureObject not found.

### ISSUE THREAD

**Issue by jqno** [danielnixon/playwarts#20]
We're trying to upgrade PlayWarts from 0.12 to 0.15 in our project. (Sadly, we can't upgrade to Play 2.5 just yet.) We get the stacktrace below. It's not specific to AkkaObject; the playwart it fails on is always the first one that's declared in the build.sbt.

On a vanilla Play 2.4 project, everything works just fine, so there must be something wrong in our project. Maybe a conflicting dependency. However, based on the stacktrace, I have no idea where to start looking. I was hoping maybe you could provide some insight.

```
scala.ScalaReflectionException: object org.danielnixon.playwarts.AkkaObject not found.
    at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:162)
    at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:22)
    at org.brianmckenna.wartremover.Plugin.getTraverser(Plugin.scala:20)
    at org.brianmckenna.wartremover.Plugin$$anonfun$ts$1$1.apply(Plugin.scala:41)
    at org.brianmckenna.wartremover.Plugin$$anonfun$ts$1$1.apply(Plugin.scala:41)
    at scala.collection.immutable.List.map(List.scala:273)
    at org.brianmckenna.wartremover.Plugin.ts$1(Plugin.scala:41)
    at org.brianmckenna.wartremover.Plugin.processOptions(Plugin.scala:45)
    at scala.tools.nsc.plugins.Plugin.init(Plugin.scala:65)
    at scala.tools.nsc.plugins.Plugins$$anonfun$loadPlugins$5.apply(Plugins.scala:99)
    at scala.tools.nsc.plugins.Plugins$$anonfun$loadPlugins$5.apply(Plugins.scala:99)
    at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
    at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
    at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
    at scala.tools.nsc.plugins.Plugins$class.loadPlugins(Plugins.scala:99)
    at scala.tools.nsc.Global.loadPlugins(Global.scala:39)
    at scala.tools.nsc.plugins.Plugins$class.plugins(Plugins.scala:102)
    at scala.tools.nsc.Global.plugins$lzycompute(Global.scala:39)
    at scala.tools.nsc.Global.plugins(Global.scala:39)
    at scala.tools.nsc.plugins.Plugins$class.computePluginPhases(Plugins.scala:113)
    at scala.tools.nsc.Global.computePluginPhases(Global.scala:39)
    at scala.tools.nsc.Global.computePhaseDescriptors(Global.scala:750)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at xsbt.CachedCompiler0$Compiler.superCall(CompilerInterface.scala:220)
    at xsbt.CachedCompiler0$Compiler.superComputePhaseDescriptors(CompilerInterface.scala:213)
    at xsbt.CachedCompiler0$Compiler.phaseDescriptors$lzycompute(CompilerInterface.scala:210)
    at xsbt.CachedCompiler0$Compiler.phaseDescriptors(CompilerInterface.scala:205)
    at scala.tools.nsc.Global$Run.<init>(Global.scala:1237)
    at xsbt.CachedCompiler0$$anon$2.<init>(CompilerInterface.scala:106)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
    at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
    at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
    at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
    at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
    at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
    at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
    at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:68)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:67)
    at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:95)
    at sbt.inc.Incremental$.compile(Incremental.scala:67)
    at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
    at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
    at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
    at sbt.Compiler$.compile(Compiler.scala:152)
    at sbt.Compiler$.compile(Compiler.scala:138)
    at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:860)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:851)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:849)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by danielnixon** [comment]
Hmmm. 0.15 was the first version that was an actual sbt plugin. The plugin basically does:

``` scala
  override lazy val projectSettings = Seq(
    libraryDependencies += "org.danielnixon" % "playwarts_2.11" % version,
    wartremoverClasspaths += Seq(
      s"file:$home/.ivy2/cache/org.danielnixon/playwarts_2.11/jars/playwarts_2.11-$version.jar"
    )
  )
```

Is your ivy cache elsewhere?

**Comment by jqno** [comment]
No, that's exactly where my ivy cache is. It now contains both playwarts_2.11-0.12.jar and playwarts_2.11-0.15.jar.

**Comment by jqno** [comment]
I did some more digging. The first thing I noticed is that, if I include Playwarts 0.15 the "old-fashioned" way (by manually adding the reference to the Ivy cache), I get the same error. I was able to include Playwarts 0.15 the old-fashioned way in a "clean" project, and that worked. So I guess the problem occurs in Playwarts itself, not in the sbt plugin part.

Then I binary-searched on our build.sbt (i.e., taking half out and see what works, then taking out more or putting it back in :) ). It turns out that the Typesafe Reactive Platform is the thing that bites with Playwarts. The Typesafe RP is a tool from Typesafe (well, Lightbend I suppose) that we use that manages the versions of the Play Framework and Slick. The RP takes care of tracking security issues in the versions for these dependencies.

I have no idea how this causes the above stacktrace, though.

**Comment by danielnixon** [comment]
I've created a project using Typesafe Reactive Platform, Play, WartRemover and PlayWarts here: https://github.com/danielnixon/test-reactive-platform

I've enabled `PlayWart.FutureObject` (`wartremoverErrors += PlayWart.FutureObject` in `build.sbt`).

It compiles okay for me. I'm not sure what I've missed. Could you tweak that project until it reproduces the issue?

**Comment by jqno** [comment]
Thanks for getting back to me about this.

I feel a little silly now. Your message has triggered me to revisit the issue in our code base, and it looks like it doesn't have much to do with the Reactive Platform after all. 😅 Of course, many things have changed in our code base, and also our code base's environment, in the mean time, and I could swear removing the RP back then fixed the issue for us. But now it no longer does, and if I go back to a commits of around the time I filed this issue, it doesn't either.

However, I did manage to reproduce the issue that we had then, and I was able to make a small SBT file for the project you provide that also reproduces it. See the pull request to your test project. As you can see, we've tried to separate the WartRemover/PlayWarts cycle from the regular compile cycle. You can trigger the error by calling `sbt lint:compile`. I was following Eugene Yakota's example from [this StackOverflow answer](http://stackoverflow.com/a/27630768/127863).

And now I must admit to feeling even sillier, because I also found the line that caused the problem: line 27, which adds `Defaults.compileSettings` to the settings (which came from Yakota's code as well). If I remove it, the problem goes away again, and it does in our real build script too. (In my defense, our build is big enough that it took me about 3 hours to figure this out today 😉. We have a complex build.)

I'll open the pull request so you can take a look at the issue yourself; maybe you can get something out of it. For us, the issue is now resolved, so you can close the issue if you like. I'm very sorry if you spent a lot of time on this...

**Comment by jqno** [comment]
It seems I've forgotten about this issue. In the mean time, the problem has become irrelevant, since we've upgraded to Play 2.5, we're no longer using the Typesafe Reactive Platform, and we've also changed the way we run WartRemover in our build. (No longer though the `sbt lint:compile` task I mentioned above.)
We're now successfully using PlayWarts 0.28.

I'll close the issue now.
